### ISSUE TITLE
Generating Hi-C contact matrix with Hi-C reads from multiple libraries

### ISSUE THREAD

**Issue by Raina-M** [koszullab/hicstuff#34]
Hello there,
I would like to generate Hi-C  contact matrix to feed into instaGRAAL, but I am working with the Hi-C reads from different libraries, to be more specific, the Hi-C reads include both biological and technical replicates. The following list is the Hi-C reads I got, in which `1M` and `2M` mean the samples were from 2 different individuals (biological replicates). And for each individual you can also see different library names, for instance, Hi-C reads of `1M` were from 2 PCR runs  `mpimg_L15002-1` and `mpimg_L15003-1` (technical replicates). 

> mpimg_L15002-1_NMR-L1-1M-R1_S9_R1_001.fastq.gz
> mpimg_L15002-1_NMR-L1-1M-R1_S9_R2_001.fastq.gz
> mpimg_L15003-1_NMR-L1-1M-R2_S1_R1_001.fastq.gz
> mpimg_L15003-1_NMR-L1-1M-R2_S1_R2_001.fastq.gz
> mpimg_L15003-1_NMR-L1-1M-R2_S10_R1_001.fastq.gz
> mpimg_L15003-1_NMR-L1-1M-R2_S10_R2_001.fastq.gz
> mpimg_L15004-1_NMR-L1-2M-R1_S2_R1_001.fastq.gz
> mpimg_L15004-1_NMR-L1-2M-R1_S2_R2_001.fastq.gz
> mpimg_L15004-1_NMR-L1-2M-R1_S11_R1_001.fastq.gz
> mpimg_L15004-1_NMR-L1-2M-R1_S11_R2_001.fastq.gz
> mpimg_L15005-1_NMR-L1-2M-R2_S3_R1_001.fastq.gz
> mpimg_L15005-1_NMR-L1-2M-R2_S3_R2_001.fastq.gz
> mpimg_L15005-1_NMR-L1-2M-R2_S12_R1_001.fastq.gz
> mpimg_L15005-1_NMR-L1-2M-R2_S12_R2_001.fastq.gz

So, how should I deal with multiple Hi-C reads like above? What comes intuitively to me is that feed all forward reads (*R1_001) to `input1` and all reverse reads (*R2_001) to `input2`, but I did not find any evidence that `hicstuff pipeline` supports a list of inputs. Am I supposed to merge the reads before applying `hicstuff pipeline`? Or run the pipeline for each replicates at first and then merge the output contact matrices? because there is an option in `pipeline`: `-D, --duplicates` to filter out PCR duplicates, I am not sure whether this argument would affect my technical replicates. But the output matrices are normalized, right? Then I have to normalize the merged matrix again manually ...
In a word, do you have any suggestions to tackle this situation?

**Comment by cmdoret** [comment]
Hello Raina, 

You are right, hicstuff does not support a list of inputs, it only takes 2 fastq files.
Since you plan to use those samples for genome assembly, it should be perfectly fine to merge the fastq. You could just merge all your different replicates using :
```bash
cat *_R1* > samples_R1.fastq.gz
cat *_R2* > samples_R2.fastq.gz
```
As long as the replicates are merged in the same order in R1 and R2, hicstuff should handle them properly. I don't think PCR duplicates are really a problem for genome assembly.

Matrices generated by hicstuff are not normalized, and instagraal takes raw matrices as input, so in theory if you generated multiple matrice separately you could just add them up (as long as the libraries have been processed with the same enzymes).

Tell me if you need more help :)

**Comment by Raina-M** [comment]
Thank you @cmdoret !
That helps me a lot, I think I will just merge the reads before feeding into hicstuff.
