### ISSUE TITLE
Support for OmniC data

### ISSUE THREAD

**Issue by diriano** [koszullab/hicstuff#53]
Does hicstuff supports Dovetail's OmniC data?

**Comment by cmdoret** [comment]
Hi @diriano 

In principle, hicstuff will work for OmniC data. However, until now there was no way to filter out spurious events in Omni-C like we do for Hi-C.

I have just release v3.1.0 which allows to set `--enzyme=mnase` in `hicstuff pipeline`. This will bin at 100bp and filter out spurious short range events.

By default, the filter is not enabled, to filter these out, you need to specify the `--filter` option. Since this is a bit experimental, we would love to have feedback from you, on whether enabling `--filter` improved your maps.
