### ISSUE TITLE
Error with rebin function

### ISSUE THREAD

**Issue by aurelepiazza** [koszullab/hicstuff#81]
Hi,
I got the following error with the latest (3.2.3) version of hicstuff trying to run the rebin function (which worked with previous versions):
Traceback (most recent call last):
  File "/home/apiazza/miniforge3/envs/hicstuff323/bin/hicstuff", line 8, in <module>
    sys.exit(main())
  File "/home/apiazza/miniforge3/envs/hicstuff323/lib/python3.10/site-packages/hicstuff/main.py", line 57, in main
    command.execute()
  File "/home/apiazza/miniforge3/envs/hicstuff323/lib/python3.10/site-packages/hicstuff/commands.py", line 1108, in execute
    hic_map, _ = hcs.bin_bp_sparse(hic_map, frags.start_pos, binning)
**AttributeError: module 'hicstuff.stats' has no attribute 'bin_bp_sparse'**

Not sure what this is due to, as the arguments do not seem to have changed.
Thanks a lot in advance for your help.

**Comment by js2264** [comment]
Thx for the issue, it comes from a minor mistake which is now fixed in https://github.com/koszullab/hicstuff/commit/343d58e8e437413bc784681a690e0af7f255f0c4. I bumped the version to `3.2.4`. This will take some time to propagate to `bioconda`. In the meantime, you can install `3.2.4` using: 

```{shell}
pip3 install -e git+https://github.com/koszullab/hicstuff.git@master#egg=hicstuff
```

Of note, `rebin` still has an unfixed bug, see https://github.com/koszullab/hicstuff/issues/79. The current best approach is to bin from a pairs file using `cooler cload`.
